

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    env_file:
      - .env
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  spark-processor:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark_processor
    depends_on:
      - kafka
      - postgres
    env_file:
      - .env
    environment:
      # Spark container in Docker network needs to talk to Kafka internal port
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      # BigQuery credentials (mount file bên dưới volumes)
      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials/service-account.json
      # PostgreSQL (inside Docker network)
      POSTGRES_HOST: postgres
      # Override host Windows JAVA_HOME to Linux path
      JAVA_HOME: "/usr"
    volumes:
      # Mount thư mục chứa Service Account JSON vào container
      - ./credentials:/app/credentials:ro
      # Mount thư mục để Spark ghi Parquet backup cho BigQuery Load Job
      - ./bq_backup:/tmp/bq_backup

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: binance_dw
      POSTGRES_USER: binance
      POSTGRES_PASSWORD: binance123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c synchronous_commit=off -c max_wal_size=4GB -c min_wal_size=1GB -c checkpoint_completion_target=0.9

volumes:
  postgres_data:
